app/events/models.py
from app import db
from flask import current_app as app
from sqlalchemy.orm import column_property
from sqlalchemy import desc, asc
from datetime import date

class Event(db.Model):
    __tablename__ = 'events'

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    date = db.Column(db.Date())
    host = db.Column(db.Integer())
    location = db.Column(db.Integer())
    price = db.Column(db.Integer())
    details = db.Column(db.String())

    def __eq__(self, other):
        return self.name

    def __ne__(self, other):
        return self.name

    def __hash__(self):
        return hash(self.name)

    def __str__(self):
        return self.name

    @classmethod
    def get_sortable_list(cls, order, direction, page):
        per_page = app.config["ADMIN_PER_PAGE"]
        if direction == 'desc':
            o = desc(order)
        else:
            o = asc(order)
        return Event.query.order_by(o).paginate(page, per_page, error_out=False)


    @classmethod
    def get_upcoming(cls):
        return db.session.query(cls).filter(Event.date >= date.today()).all()

    @classmethod
    def all(cls):
        return db.session.query(cls).all()

app/events/controllers.py
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, abort, jsonify
)
import app.events.models as EventsModels
from app import db

events = Blueprint('events', __name__, url_prefix='/events')


@events.route('/', methods=['GET'])
def index():
    events = EventsModels.Event.get_upcoming()
    if request.args.get('ajax'):
        data = []
        for event in events:
            if event.price is 0:
                price = ''
            else:
                price = "$" + str(event.price)

            data_set = [event.name,
                event.date.strftime("%m/%d/%Y (%A)"),
                event.host,
                event.location,
                price]

            data_set.append(render_template('/events/view_event.html',
                event_id=event.id))

            data.append(data_set)

        return jsonify({'data': data})
    return render_template("/events/index.html", events=events)


@events.route('/event/<int:event_id>', methods=['GET'])
def event(event_id):
    event = EventsModels.Event.query.get(event_id)
    return render_template("/events/event.html", event=event)

app/templates/events/event.html
{% extends "base.html" %}
{% block title %}Event{% endblock %}

{% block content %}
<div class="ui one column grid container">
  <div class="column">
    <h1>Event Details</h1>
    {% if event %}
      <h3>{{ event.name }}</h3>
      <p>Host: {{ event.host }}</p>
      <p>Location: {{ event.location }}</h3>
      <p>Date: {{ event.date }}</p>
      {% if event.price %}<p>Price: ${{ event.price }}</p>{% endif %}
      <p>Info: {{ event.details|safe }}</p>
    {% else %}
      <h3>Event not found</h3>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/events/index.html
{% extends "base.html" %}
{% block title %}Events{% endblock %}

{% block content %}
<div class="ui one column grid container">
    <div class="column">
      <h1>Events</h1>
      <p>If we're missing an event please join the <a target="_blank" href="https://discord.gg/fH7fJUKgX9">Discord</a> and message us, or find us on <a target="_blank" href="https://www.instagram.com/drift_norcal/">Instagram</a> and let us know!</p>
      <table class="ui striped table" style="width: 100%;">
          <thead>
            <tr>
              <th>Name</th>
              <th>Date</th>
              <th>Host</th>
              <th>Location</th>
              <th>Price</th>
              <th>View Details</th>
            </tr>
        </thead>
    </table>
    </div>
</div>
{% endblock %}


{% block script %}
<script>
  $(document).ready(function(){
    $('table.striped.table').DataTable( {
          "ajax": "{{ url_for('events.index', ajax=1) }}",
          order: [[1, 'asc']],
      });
  })
</script>
{% endblock %}

app/templates/events/view_event.html
<a class='ui blue vertical animated button' href="{{ url_for('events.event', event_id=event_id ) }}">
	<div class="hidden content">View</div>
	<div class="visible content">
		<i class="table icon" aria-hidden="true"></i>
	</div>
</a>