app/admin/controllers.py
# Import flask dependencies
from datetime import datetime

import flask_login as login
from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_admin import helpers
from werkzeug.security import generate_password_hash

from app import db
import app.admin.forms as AdminForms
import app.auth.models as AuthModels
import app.events.models as EventsModels
import app.media.models as MediaModels
from app.helpers.decorators import check_admin, check_login, has_role
from app.helpers.utils import slugify

# Create blog blueprint
admin = Blueprint('admin', __name__, url_prefix='/admin')


@admin.route('/', methods=['GET'])
@check_login
@check_admin
def index():
    return render_template("admin/index.html")


# Create the user routes
@admin.route('/user', defaults={'page': 1}, methods=['GET'])
@admin.route('/user/<int:page>', methods=['GET'])
@check_login
@check_admin
def user_list(page):
    order = 'users_' + request.args[
        'sort'] if 'sort' in request.args else 'users_id'
    direction = request.args['d'] if 'd' in request.args else 'desc'
    users = AuthModels.User.get_sortable_list(order, direction, page)

    return render_template("admin/users/list.html", users=users)


@admin.route('/user/create', methods=['GET', 'POST'])
@check_login
@check_admin
def create_user():
    form = AdminForms.CreateUserForm(request.form)
    if helpers.validate_form_on_submit(form):
        user = AuthModels.User()
        form.populate_obj(user)
        user.password = generate_password_hash(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('admin.user_list'))

    return render_template("admin/users/user.html", form=form)


@admin.route('/user/edit/<int:user_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit_user(user_id):
    user = AuthModels.User.query.get(user_id)
    old_pass = user.password
    user.password = None
    last_login = user.last_login_ip
    form = AdminForms.EditUserForm(request.form, obj=user)
    if helpers.validate_form_on_submit(form):

        form.populate_obj(user)

        if user.password == '':
            user.password = old_pass
        else:
            user.password = generate_password_hash(user.password)

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('admin.user_list'))

    return render_template("admin/users/user.html", form=form,
                           last_login=last_login)


@admin.route('/user/delete/<int:user_id>', methods=['GET'])
@check_login
@check_admin
def delete_user(user_id):
    user = AuthModels.User.query.get_or_404(user_id)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('admin.user_list'))


# Create the role routes
@admin.route('/role', defaults={'page': 1}, methods=['GET'])
@admin.route('/role/<int:page>', methods=['GET'])
@check_login
@check_admin
def role_list(page):
    order = request.args['sort'] if 'sort' in request.args else 'id'
    direction = request.args['d'] if 'd' in request.args else 'desc'
    roles = AuthModels.Role.get_sortable_list(order, direction, page)

    return render_template("admin/roles/list.html", roles=roles)


@admin.route('/role/create', methods=['GET', 'POST'])
@check_login
@check_admin
def create_role():
    form = AdminForms.CreateRoleForm(request.form)
    if helpers.validate_form_on_submit(form):
        role = Role()
        form.populate_obj(role)
        db.session.add(role)
        db.session.commit()
        return redirect(url_for('admin.role_list'))

    return render_template("admin/roles/role.html", form=form)


@admin.route('/role/edit/<int:role_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit_role(role_id):
    role = AuthModels.Role.query.get(role_id)
    form = AdminForms.EditRoleForm(request.form, obj=role)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(role)
        db.session.add(role)
        db.session.commit()
        return redirect(url_for('admin.role_list'))

    return render_template("admin/roles/role.html", form=form)


@admin.route('/role/delete/<int:role_id>', methods=['GET'])
@check_login
@check_admin
def delete_role(role_id):
    role = AuthModels.Role.query.get_or_404(role_id)
    db.session.delete(role)
    db.session.commit()
    return redirect(url_for('admin.role_list'))


# Create the event routes
@admin.route('/event', defaults={'page': 1}, methods=['GET'])
@admin.route('/event/<int:page>', methods=['GET'])
@check_login
@check_admin
def event_list(page):
    order = request.args['sort'] if 'sort' in request.args else 'id'
    direction = request.args['d'] if 'd' in request.args else 'desc'
    events = EventsModels.Event.get_sortable_list(order, direction, page)

    return render_template("admin/events/list.html", events=events)


@admin.route('/event/create', methods=['GET', 'POST'])
@check_login
@check_admin
def create_event():
    form = AdminForms.CreateEventForm(request.form)
    if helpers.validate_form_on_submit(form):
        event = EventsModels.Event()
        form.populate_obj(event)
        db.session.add(event)
        db.session.commit()
        return redirect(url_for('admin.event_list'))

    return render_template("admin/events/event.html", form=form)


@admin.route('/event/edit/<int:event_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit_event(event_id):
    event = EventsModels.Event.query.get(event_id)
    form = AdminForms.EditEventForm(request.form, obj=event)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(event)
        db.session.add(event)
        db.session.commit()
        return redirect(url_for('admin.event_list'))

    return render_template("admin/events/event.html", form=form)


@admin.route('/event/delete/<int:event_id>', methods=['GET'])
@check_login
@check_admin
def delete_event(event_id):
    event = EventsModels.Event.query.get_or_404(event_id)
    db.session.delete(event)
    db.session.commit()
    return redirect(url_for('admin.event_list'))


# Create the media routes
@admin.route('/media', defaults={'page': 1}, methods=['GET'])
@admin.route('/media/<int:page>', methods=['GET'])
@check_login
@check_admin
def media_list(page):
    order = request.args['sort'] if 'sort' in request.args else 'id'
    direction = request.args['d'] if 'd' in request.args else 'desc'
    media = MediaModels.Media.get_sortable_list(order, direction, page)

    return render_template("admin/media/list.html", media=media)


@admin.route('/media/create', methods=['GET', 'POST'])
@check_login
@check_admin
def create_media():
    form = AdminForms.CreateMediaForm(request.form)
    if helpers.validate_form_on_submit(form):
        media = MediaModels.Media()
        form.populate_obj(media)
        db.session.add(media)
        db.session.commit()
        return redirect(url_for('admin.media_list'))

    return render_template("admin/media/media.html", form=form)


@admin.route('/media/edit/<int:media_id>', methods=['GET', 'POST'])
@check_login
@check_admin
def edit_media(media_id):
    media = MediaModels.Media.query.get(media_id)
    form = AdminForms.EditMediaForm(request.form, obj=media)
    if helpers.validate_form_on_submit(form):
        form.populate_obj(media)
        db.session.add(media)
        db.session.commit()
        return redirect(url_for('admin.media_list'))

    return render_template("admin/media/media.html", form=form)


@admin.route('/media/delete/<int:media_id>', methods=['GET'])
@check_login
@check_admin
def delete_media(media_id):
    media = MediaModels.Media.query.get_or_404(media_id)
    db.session.delete(media)
    db.session.commit()
    return redirect(url_for('admin.media_list'))

app/media/controllers.py
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, abort, jsonify
)
import app.media.models as MediaModels
from app import db

media = Blueprint('media', __name__, url_prefix='/media')


@media.route('/', methods=['GET'])
def index():
    media = MediaModels.Media.all()
    if request.args.get('ajax'):
        data = []
        for m in media:

            data_set = []

            data_set.append(render_template('/media/instagram.html',
                instagram=m.instagram))
            data_set.append(render_template('/media/website.html',
                website=m.website))
            data_set.append(m.locations)
            data_set.append(m.types)

            data.append(data_set)

        return jsonify({'data': data})
    return render_template("/media/index.html", media=media)

app/shops/controllers.py
from flask import (
    Blueprint, request, render_template,
    redirect, url_for, abort,
)
import app.shops.models as ShopsModels
from app import db

shops = Blueprint('shops', __name__, url_prefix='/shops')


@shops.route('/', methods=['GET'])
def index():
    return render_template("/shops/index.html")

app/site/controllers.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, url_prefix='')


@site.route('/', methods=['GET'])
def index():
    return render_template("/site/index.html")

app/templates/base.html
{% import 'layout.html' as layout with context -%}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.css" />
    <style>
      .ui.secondary.inverted.pointing.menu{
        border: none;
      }
      .secondary.pointing.menu .toc.item {display: none;}
      .ui.grid{
	    margin: 30px 0;
       }
      @media only screen and (max-width: 700px) {
          .secondary.pointing.menu .item, .secondary.pointing.menu .right.item {display: none;}
          .secondary.pointing.menu .toc.item {display: block;}
      }
    </style>
    {% block style %}{% endblock %}
    {% endblock %}
</head>
<body class="pushable">
    {{ layout.mobile_menu() }}
    <div class="pusher">
        <div class="ui inverted vertical masthead segment">
            {{ layout.menu() }}
        </div>      
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
              <div class="ui inline cookie nag" style="margin-top: -30px; margin-bottom: 15px;">
                <span class="title">{{ message }}</span>
                <i class="close icon"></i>
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}

        {{ layout.footer() }}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.8.8/semantic.min.js"></script>
    <script src='https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js'></script>
    <script src='https://cdn.datatables.net/1.12.1/js/dataTables.semanticui.min.js'></script>
    <script>
      $(document).ready(function() {
        // create sidebar and attach to menu open
        $('.ui.sidebar').sidebar('attach events', '.toc.item');
        // show nag (flash) messages
        $('.cookie.nag').nag('show');
        // init dropdowns
        $('.ui.dropdown').dropdown();
        $('.ui.accordion').accordion();
      });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

app/templates/layout.html
{% macro menu() -%}
<div class="ui container">
  <div class="ui large inverted secondary pointing menu">
    <a class="toc item">
      <i class="sidebar icon"></i>
    </a>
    <a class="header item inverted" href="{{ url_for('site.index') }}">Drift NorCal</a>

    <div class="right item" style='padding: 0;'>
      <a class="item inverted {%- if request.path == url_for('events.index') %} active{% endif %}" href="{{ url_for('events.index') }}">Events</a>
      <a class="item inverted {%- if request.path == url_for('media.index') %} active{% endif %}" href="{{ url_for('media.index') }}">Media</a>
      <a class="item inverted {%- if request.path == url_for('shops.index') %} active{% endif %}" href="{{ url_for('shops.index') }}">Shops</a>
      <a class="item inverted" target="_blank" href="https://discord.gg/fH7fJUKgX9">Community</a>
      {% if current_user.is_authenticated %}
        <div class="ui right dropdown item">
          <i class='user icon' aria-hidden="true"></i>
          <i class="dropdown icon" aria-hidden="true"></i>
          <div class="menu">
            <a class="item" href="{{ url_for('admin.index') }}">Admin</a>
            <a class="item" href="{{ url_for('auth.logout_view') }}">Logout</a>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{%- endmacro %}

{% macro mobile_menu() -%}
<div class="ui vertical inverted sidebar menu left">
    <a class="item {%- if request.path == url_for('site.index') %} active{% endif %}" href="{{ url_for('site.index') }}">Drift NorCal</a>
    <a class="item {%- if request.path == url_for('events.index') %} active{% endif %}" href="{{ url_for('events.index') }}">Events</a>
    <a class="item {%- if request.path == url_for('media.index') %} active{% endif %}" href="{{ url_for('media.index') }}">Media</a>
    <a class="item {%- if request.path == url_for('shops.index') %} active{% endif %}" href="{{ url_for('shops.index') }}">Shops</a>
    <a class="item" target="_blank" href="https://discord.gg/8qrHdhjGy4">Community</a>
</div>
{%- endmacro %}

{% macro footer() -%}
<div class="ui vertical footer segment m">
    <div class="ui center aligned text container">
      <div class="row">
        <p><i class='copyright icon'></i> {{ now.year }} Drift NorCal</p>
        <a target="_blank" href="https://www.instagram.com/drift_norcal/"><i class="instagram black big icon"></i></a>
        <a target="_blank" href="https://discord.gg/fH7fJUKgX9"><i class="discord black big icon"></i></a>
      </div>
    </div>
  </div>
{%- endmacro %}